[versions]
activityCompose = "1.10.1"
cameraCore = "1.4.2"
composeBom = "2025.06.00"
constraintlayout = "2.2.1"
coreKtx = "1.16.0"
appcompat = "1.7.1"
espressoCore = "3.6.1"
foundation = "1.8.2"
junit = "4.13.2"
junitVersion = "1.2.1"
kotlinxCoroutinesGuava = "1.10.2"
lifecycleRuntimeKtx = "2.9.1"
material = "1.12.0"
kotlinStdlib = "2.1.21"
annotation = "1.9.1"
material3 = "1.3.2"
multidex = "2.0.1"
uiToolingPreview = "1.8.2"
composeUi = "1.8.2"
kotlin = "2.1.20"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version = "1.12.0-alpha02" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version = "1.7.1" }
androidx-camera-camera2 = { module = "androidx.camera:camera-camera2", version = "1.5.0-beta01" }
androidx-camera-core = { module = "androidx.camera:camera-core", version = "1.5.0-beta01" }
androidx-camera-lifecycle = { module = "androidx.camera:camera-lifecycle", version = "1.5.0-beta01" }
androidx-camera-view = { module = "androidx.camera:camera-view", version = "1.5.0-beta01" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version = "2025.06.00" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version = "2.2.1" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version = "1.16.0" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version = "3.7.0-alpha03" }
androidx-foundation = { module = "androidx.compose.foundation:foundation", version = "1.9.0-alpha04" }
androidx-junit = { module = "androidx.test.ext:junit", version = "1.3.0-alpha03" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version = "2.9.1" }
androidx-material3 = { module = "androidx.compose.material3:material3", version = "1.4.0-alpha15" }
androidx-multidex = { module = "androidx.multidex:multidex", version.ref = "multidex" }
androidx-ui = { module = "androidx.compose.ui:ui", version = "1.9.0-alpha04" }
androidx-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version = "1.9.0-alpha04" }
junit = { module = "junit:junit", version = "4.13.2" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version = "2.2.0-RC2" }
kotlinx-coroutines-guava = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-guava", version = "1.10.2" }
material = { module = "com.google.android.material:material", version = "1.14.0-alpha01" }
androidx-annotation = { group = "androidx.annotation", name = "annotation", version.ref = "annotation" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics", version = "1.9.0-alpha04" }
ui = { module = "androidx.compose.ui:ui", version = "1.9.0-alpha04" }
[plugins]
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

